plugins {
    id 'com.android.application'
}

android {
    namespace 'center.mingo.exoticszoo'
    compileSdk 35

    defaultConfig {
        applicationId 'center.mingo.exoticszoo'
        minSdk 24
        targetSdk 35
        versionCode 13
        versionName 'B13'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['META-INF/DEPENDENCIES', 'META-INF/LICENSE*', 'META-INF/NOTICE*']
        }
    }
}
