#include "CoreGenerator.hpp"
#include "EngineGenerator.hpp"
#include "../Utils/FileWriter.hpp"
#include <filesystem>
namespace exotic { void CoreGenerator::Generate(){ std::filesystem::create_directories("Core"); EngineGenerator::Generate("Memory"); EngineGenerator::Generate("Observer"); EngineGenerator::Generate("Execution"); EngineGenerator::Generate("Prediction"); EngineGenerator::Generate("Alignment"); FileWriter::Write("Core/README.md","# EXOTIC CORE\n\nGenerated by Exotic Builder.\n\n## Core Engines\n\n- MemoryEngine\n- ObserverEngine\n- ExecutionEngine\n- PredictionEngine\n- AlignmentEngine\n\n## Flow\n\nObserve  Map  Predict  Align  Act  Measure  Learn\n"); } }
