#include "exotic/cognition/adaptation_applier.hpp"
#include "exotic/cognition/stable_id.hpp"
#include "exotic/cognition/storage_schema.hpp"
#include <sqlite3.h>
#include <algorithm>
#include <stdexcept>
namespace exotic::cognition { namespace {
void ck(int rc,sqlite3*db,const char*w){if(rc!=SQLITE_OK&&rc!=SQLITE_DONE&&rc!=SQLITE_ROW)throw std::runtime_error(std::string(w)+": "+sqlite3_errmsg(db));}
std::string target_name(AdaptationTarget t){switch(t){case AdaptationTarget::Belief:return"belief";case AdaptationTarget::Preference:return"preference";case AdaptationTarget::Drive:return"drive";case AdaptationTarget::Strategy:return"strategy";default:return"goal";}}
AdaptationTarget parse_target(const std::string&s){if(s=="belief")return AdaptationTarget::Belief;if(s=="preference")return AdaptationTarget::Preference;if(s=="drive")return AdaptationTarget::Drive;if(s=="strategy")return AdaptationTarget::Strategy;return AdaptationTarget::Goal;}
struct DB{sqlite3*d{};explicit DB(const std::string&p){ck(sqlite3_open(p.c_str(),&d),d,"open adaptation history");try{apply_storage_migrations(d);}catch(...){sqlite3_close(d);d=nullptr;throw;}}~DB(){if(d)sqlite3_close(d);}};
void bind_text(sqlite3_stmt*s,int i,const std::string&v){sqlite3_bind_text(s,i,v.c_str(),-1,SQLITE_TRANSIENT);}double clamp01(double v){return std::clamp(v,0.0,1.0);} }
bool AdaptationApplier::apply(const AdaptationChoice&choice,const std::string&created_at,std::string rationale){if(choice.decision!=AdaptationDecision::Adopt)return false;const auto&p=choice.proposal;double before=0,after=0;bool found=false;if(p.target==AdaptationTarget::Preference){for(auto x:store_.preferences())if(x.key==p.target_id){before=x.weight;x.weight=clamp01(x.weight+p.suggested_delta);after=x.weight;store_.set_preference(x);found=true;break;}}else if(p.target==AdaptationTarget::Drive){for(auto x:store_.drives())if(x.key==p.target_id){before=x.level;x.level=clamp01(x.level+p.suggested_delta);after=x.level;store_.set_drive(x);found=true;break;}}else if(p.target==AdaptationTarget::Belief){for(auto x:store_.beliefs())if(x.id==p.target_id){before=x.confidence;x.confidence=clamp01(x.confidence+p.suggested_delta);x.evidence += x.evidence.empty()?"adaptation":"; adaptation";x.updated_at=created_at;after=x.confidence;store_.upsert_belief(x);found=true;break;}}else if(p.target==AdaptationTarget::Goal){for(auto x:store_.goals())if(x.id==p.target_id){before=x.priority;x.priority=clamp01(x.priority+p.suggested_delta);after=x.priority;store_.upsert_goal(x);found=true;break;}}else return false;if(!found)return false;DB db(store_.path());sqlite3_stmt*s{};ck(sqlite3_prepare_v2(db.d,"INSERT INTO adaptation_history VALUES(?,?,?,?,?,?,?,0);",-1,&s,nullptr),db.d,"insert prepare");auto id=stable_id("adaptation");bind_text(s,1,id);bind_text(s,2,target_name(p.target));bind_text(s,3,p.target_id);sqlite3_bind_double(s,4,before);sqlite3_bind_double(s,5,after);bind_text(s,6,rationale.empty()?choice.rationale:rationale);bind_text(s,7,created_at);ck(sqlite3_step(s),db.d,"insert");sqlite3_finalize(s);return true;}
bool AdaptationApplier::rollback(const std::string&history_id,const std::string&reason){DB db(store_.path());sqlite3_stmt*s{};ck(sqlite3_prepare_v2(db.d,"SELECT target,target_id,before_value,rolled_back FROM adaptation_history WHERE id=?;",-1,&s,nullptr),db.d,"rollback select");bind_text(s,1,history_id);if(sqlite3_step(s)!=SQLITE_ROW){sqlite3_finalize(s);return false;}std::string t=reinterpret_cast<const char*>(sqlite3_column_text(s,0));std::string id=reinterpret_cast<const char*>(sqlite3_column_text(s,1));double before=sqlite3_column_double(s,2);bool rolled=sqlite3_column_int(s,3)!=0;sqlite3_finalize(s);if(rolled)return false;bool found=false;auto target=parse_target(t);if(target==AdaptationTarget::Preference){for(auto x:store_.preferences())if(x.key==id){x.weight=before;store_.set_preference(x);found=true;break;}}else if(target==AdaptationTarget::Drive){for(auto x:store_.drives())if(x.key==id){x.level=before;store_.set_drive(x);found=true;break;}}else if(target==AdaptationTarget::Belief){for(auto x:store_.beliefs())if(x.id==id){x.confidence=before;x.evidence += "; rollback: "+reason;store_.upsert_belief(x);found=true;break;}}else if(target==AdaptationTarget::Goal){for(auto x:store_.goals())if(x.id==id){x.priority=before;store_.upsert_goal(x);found=true;break;}}if(!found)return false;ck(sqlite3_prepare_v2(db.d,"UPDATE adaptation_history SET rolled_back=1,rationale=rationale||? WHERE id=?;",-1,&s,nullptr),db.d,"rollback update");bind_text(s,1," | rollback: "+reason);bind_text(s,2,history_id);ck(sqlite3_step(s),db.d,"rollback step");sqlite3_finalize(s);return true;}
std::vector<AdaptationHistoryRecord> AdaptationApplier::history()const{DB db(store_.path());sqlite3_stmt*s{};ck(sqlite3_prepare_v2(db.d,"SELECT id,target,target_id,before_value,after_value,rationale,created_at,rolled_back FROM adaptation_history ORDER BY rowid;",-1,&s,nullptr),db.d,"history");std::vector<AdaptationHistoryRecord>v;while(sqlite3_step(s)==SQLITE_ROW)v.push_back({reinterpret_cast<const char*>(sqlite3_column_text(s,0)),parse_target(reinterpret_cast<const char*>(sqlite3_column_text(s,1))),reinterpret_cast<const char*>(sqlite3_column_text(s,2)),sqlite3_column_double(s,3),sqlite3_column_double(s,4),reinterpret_cast<const char*>(sqlite3_column_text(s,5)),reinterpret_cast<const char*>(sqlite3_column_text(s,6)),sqlite3_column_int(s,7)!=0});sqlite3_finalize(s);return v;}
} // namespace exotic::cognition
