#include "exotic/cognition/agent_store.hpp"
#include <sqlite3.h>
#include <stdexcept>
#include <utility>
namespace exotic::cognition { namespace {
void check(int rc,sqlite3* db,const char* w){if(rc!=SQLITE_OK&&rc!=SQLITE_DONE&&rc!=SQLITE_ROW)throw std::runtime_error(std::string(w)+": "+sqlite3_errmsg(db));}
class S{public:S(sqlite3*d,const char*q):d_(d){check(sqlite3_prepare_v2(d,q,-1,&s_,nullptr),d,"prepare");}~S(){sqlite3_finalize(s_);}sqlite3_stmt* get()const{return s_;}private:sqlite3*d_{};sqlite3_stmt*s_{};};
void txt(sqlite3_stmt*s,int i,const std::string&v){sqlite3_bind_text(s,i,v.c_str(),static_cast<int>(v.size()),SQLITE_TRANSIENT);}std::string col(sqlite3_stmt*s,int i){auto*p=sqlite3_column_text(s,i);return p?reinterpret_cast<const char*>(p):"";}
} AgentStore::AgentStore(std::string p):path_(std::move(p)){check(sqlite3_open(path_.c_str(),&db_),db_,"open database");exec("PRAGMA journal_mode=WAL;PRAGMA foreign_keys=ON;PRAGMA synchronous=NORMAL;");}AgentStore::~AgentStore(){if(db_)sqlite3_close(db_);}const std::string&AgentStore::path()const noexcept{return path_;}void AgentStore::exec(const std::string&q)const{char*e=nullptr;int rc=sqlite3_exec(db_,q.c_str(),nullptr,nullptr,&e);if(rc!=SQLITE_OK){std::string m=e?e:sqlite3_errmsg(db_);sqlite3_free(e);throw std::runtime_error(m);}}
void AgentStore::initialize(){exec(R"SQL(CREATE TABLE IF NOT EXISTS identity(singleton INTEGER PRIMARY KEY CHECK(singleton=1),id TEXT NOT NULL,name TEXT NOT NULL,self_description TEXT NOT NULL,avatar_kind TEXT NOT NULL,avatar_value TEXT NOT NULL);CREATE TABLE IF NOT EXISTS beliefs(id TEXT PRIMARY KEY,proposition TEXT NOT NULL,confidence REAL NOT NULL CHECK(confidence BETWEEN 0 AND 1),evidence TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS goals(id TEXT PRIMARY KEY,title TEXT NOT NULL,priority REAL NOT NULL CHECK(priority BETWEEN 0 AND 1),source TEXT NOT NULL,status TEXT NOT NULL);CREATE TABLE IF NOT EXISTS preferences(key TEXT PRIMARY KEY,weight REAL NOT NULL CHECK(weight BETWEEN -1 AND 1));CREATE TABLE IF NOT EXISTS drives(key TEXT PRIMARY KEY,level REAL NOT NULL,target REAL NOT NULL,learning_rate REAL NOT NULL);CREATE TABLE IF NOT EXISTS rewards(id TEXT PRIMARY KEY,source TEXT NOT NULL,value REAL NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS operator_sessions(id TEXT PRIMARY KEY,operator_id TEXT NOT NULL,token_hash TEXT NOT NULL,expires_unix INTEGER NOT NULL,revoked INTEGER NOT NULL DEFAULT 0);CREATE TABLE IF NOT EXISTS thoughts(id TEXT PRIMARY KEY,subject TEXT NOT NULL,score REAL NOT NULL,reason TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS episodes(id TEXT PRIMARY KEY,summary TEXT NOT NULL,salience REAL NOT NULL,reward REAL NOT NULL,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS semantic_memory(id TEXT PRIMARY KEY,topic TEXT NOT NULL,statement TEXT NOT NULL,confidence REAL NOT NULL,source_episode TEXT NOT NULL);CREATE TABLE IF NOT EXISTS personality_traits(key TEXT PRIMARY KEY,value REAL NOT NULL CHECK(value BETWEEN 0 AND 1),plasticity REAL NOT NULL CHECK(plasticity BETWEEN 0 AND 0.25));CREATE TABLE IF NOT EXISTS reflections(id TEXT PRIMARY KEY,observation TEXT NOT NULL,lesson TEXT NOT NULL,confidence REAL NOT NULL,created_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS idx_goals_status_priority ON goals(status,priority DESC);CREATE INDEX IF NOT EXISTS idx_beliefs_confidence ON beliefs(confidence DESC);CREATE INDEX IF NOT EXISTS idx_rewards_created ON rewards(created_at DESC);)SQL");}
void AgentStore::save_identity(const AgentIdentity&v){S s(db_,"INSERT INTO identity VALUES(1,?,?,?,?,?) ON CONFLICT(singleton) DO UPDATE SET id=excluded.id,name=excluded.name,self_description=excluded.self_description,avatar_kind=excluded.avatar_kind,avatar_value=excluded.avatar_value;");txt(s.get(),1,v.id);txt(s.get(),2,v.name);txt(s.get(),3,v.self_description);txt(s.get(),4,v.avatar_kind);txt(s.get(),5,v.avatar_value);check(sqlite3_step(s.get()),db_,"identity");}AgentIdentity AgentStore::load_identity()const{S s(db_,"SELECT id,name,self_description,avatar_kind,avatar_value FROM identity WHERE singleton=1;");AgentIdentity v;if(sqlite3_step(s.get())==SQLITE_ROW)v={col(s.get(),0),col(s.get(),1),col(s.get(),2),col(s.get(),3),col(s.get(),4)};return v;}
void AgentStore::upsert_belief(const BeliefRecord&v){S s(db_,"INSERT INTO beliefs VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET proposition=excluded.proposition,confidence=excluded.confidence,evidence=excluded.evidence,updated_at=excluded.updated_at;");txt(s.get(),1,v.id);txt(s.get(),2,v.proposition);sqlite3_bind_double(s.get(),3,v.confidence);txt(s.get(),4,v.evidence);txt(s.get(),5,v.updated_at);check(sqlite3_step(s.get()),db_,"belief");}std::vector<BeliefRecord>AgentStore::beliefs()const{S s(db_,"SELECT id,proposition,confidence,evidence,updated_at FROM beliefs ORDER BY confidence DESC,id;");std::vector<BeliefRecord>o;while(sqlite3_step(s.get())==SQLITE_ROW)o.push_back({col(s.get(),0),col(s.get(),1),sqlite3_column_double(s.get(),2),col(s.get(),3),col(s.get(),4)});return o;}
void AgentStore::upsert_goal(const PersistentGoal&v){S s(db_,"INSERT INTO goals VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,priority=excluded.priority,source=excluded.source,status=excluded.status;");txt(s.get(),1,v.id);txt(s.get(),2,v.title);sqlite3_bind_double(s.get(),3,v.priority);txt(s.get(),4,v.source);txt(s.get(),5,v.status);check(sqlite3_step(s.get()),db_,"goal");}std::vector<PersistentGoal>AgentStore::goals()const{S s(db_,"SELECT id,title,priority,source,status FROM goals ORDER BY priority DESC,id;");std::vector<PersistentGoal>o;while(sqlite3_step(s.get())==SQLITE_ROW)o.push_back({col(s.get(),0),col(s.get(),1),sqlite3_column_double(s.get(),2),col(s.get(),3),col(s.get(),4)});return o;}
void AgentStore::set_preference(const PreferenceRecord&v){S s(db_,"INSERT INTO preferences VALUES(?,?) ON CONFLICT(key) DO UPDATE SET weight=excluded.weight;");txt(s.get(),1,v.key);sqlite3_bind_double(s.get(),2,v.weight);check(sqlite3_step(s.get()),db_,"preference");}std::vector<PreferenceRecord>AgentStore::preferences()const{S s(db_,"SELECT key,weight FROM preferences ORDER BY key;");std::vector<PreferenceRecord>o;while(sqlite3_step(s.get())==SQLITE_ROW)o.push_back({col(s.get(),0),sqlite3_column_double(s.get(),1)});return o;}
void AgentStore::set_drive(const DriveRecord&v){S s(db_,"INSERT INTO drives VALUES(?,?,?,?) ON CONFLICT(key) DO UPDATE SET level=excluded.level,target=excluded.target,learning_rate=excluded.learning_rate;");txt(s.get(),1,v.key);sqlite3_bind_double(s.get(),2,v.level);sqlite3_bind_double(s.get(),3,v.target);sqlite3_bind_double(s.get(),4,v.learning_rate);check(sqlite3_step(s.get()),db_,"drive");}std::vector<DriveRecord>AgentStore::drives()const{S s(db_,"SELECT key,level,target,learning_rate FROM drives ORDER BY key;");std::vector<DriveRecord>o;while(sqlite3_step(s.get())==SQLITE_ROW)o.push_back({col(s.get(),0),sqlite3_column_double(s.get(),1),sqlite3_column_double(s.get(),2),sqlite3_column_double(s.get(),3)});return o;}
void AgentStore::append_reward(const RewardEvent&v){S s(db_,"INSERT INTO rewards VALUES(?,?,?,?,?);");txt(s.get(),1,v.id);txt(s.get(),2,v.source);sqlite3_bind_double(s.get(),3,v.value);txt(s.get(),4,v.reason);txt(s.get(),5,v.created_at);check(sqlite3_step(s.get()),db_,"reward");}double AgentStore::reward_total()const{S s(db_,"SELECT COALESCE(SUM(value),0) FROM rewards;");return sqlite3_step(s.get())==SQLITE_ROW?sqlite3_column_double(s.get(),0):0;}
void AgentStore::create_session(const OperatorSession&v){S s(db_,"INSERT INTO operator_sessions VALUES(?,?,?,?,?);");txt(s.get(),1,v.id);txt(s.get(),2,v.operator_id);txt(s.get(),3,v.token_hash);sqlite3_bind_int64(s.get(),4,v.expires_unix);sqlite3_bind_int(s.get(),5,v.revoked);check(sqlite3_step(s.get()),db_,"session");}std::optional<OperatorSession>AgentStore::find_session(const std::string&id)const{S s(db_,"SELECT id,operator_id,token_hash,expires_unix,revoked FROM operator_sessions WHERE id=?;");txt(s.get(),1,id);if(sqlite3_step(s.get())!=SQLITE_ROW)return std::nullopt;return OperatorSession{col(s.get(),0),col(s.get(),1),col(s.get(),2),sqlite3_column_int64(s.get(),3),sqlite3_column_int(s.get(),4)!=0};}void AgentStore::revoke_session(const std::string&id){S s(db_,"UPDATE operator_sessions SET revoked=1 WHERE id=?;");txt(s.get(),1,id);check(sqlite3_step(s.get()),db_,"revoke");}
void AgentStore::append_thought(const std::string&id,const std::string&subject,double score,const std::string&reason,const std::string&status,const std::string&created){S s(db_,"INSERT OR REPLACE INTO thoughts VALUES(?,?,?,?,?,?);");txt(s.get(),1,id);txt(s.get(),2,subject);sqlite3_bind_double(s.get(),3,score);txt(s.get(),4,reason);txt(s.get(),5,status);txt(s.get(),6,created);check(sqlite3_step(s.get()),db_,"thought");}
void AgentStore::append_episode(const Episode&v){S s(db_,"INSERT OR REPLACE INTO episodes VALUES(?,?,?,?,?);");txt(s.get(),1,v.id);txt(s.get(),2,v.summary);sqlite3_bind_double(s.get(),3,v.salience);sqlite3_bind_double(s.get(),4,v.reward);txt(s.get(),5,v.created_at);check(sqlite3_step(s.get()),db_,"episode");}std::vector<Episode>AgentStore::episodes(std::size_t n)const{S s(db_,"SELECT id,summary,salience,reward,created_at FROM episodes ORDER BY created_at DESC LIMIT ?;");sqlite3_bind_int64(s.get(),1,static_cast<sqlite3_int64>(n));std::vector<Episode>o;while(sqlite3_step(s.get())==SQLITE_ROW)o.push_back({col(s.get(),0),col(s.get(),1),sqlite3_column_double(s.get(),2),sqlite3_column_double(s.get(),3),col(s.get(),4)});return o;}
void AgentStore::upsert_semantic_memory(const SemanticMemory&v){S s(db_,"INSERT INTO semantic_memory VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET topic=excluded.topic,statement=excluded.statement,confidence=MAX(semantic_memory.confidence,excluded.confidence),source_episode=excluded.source_episode;");txt(s.get(),1,v.id);txt(s.get(),2,v.topic);txt(s.get(),3,v.statement);sqlite3_bind_double(s.get(),4,v.confidence);txt(s.get(),5,v.source_episode);check(sqlite3_step(s.get()),db_,"semantic");}std::vector<SemanticMemory>AgentStore::semantic_memories()const{S s(db_,"SELECT id,topic,statement,confidence,source_episode FROM semantic_memory ORDER BY confidence DESC,id;");std::vector<SemanticMemory>o;while(sqlite3_step(s.get())==SQLITE_ROW)o.push_back({col(s.get(),0),col(s.get(),1),col(s.get(),2),sqlite3_column_double(s.get(),3),col(s.get(),4)});return o;}
void AgentStore::set_trait(const PersonalityTrait&v){S s(db_,"INSERT INTO personality_traits VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,plasticity=excluded.plasticity;");txt(s.get(),1,v.key);sqlite3_bind_double(s.get(),2,v.value);sqlite3_bind_double(s.get(),3,v.plasticity);check(sqlite3_step(s.get()),db_,"trait");}std::vector<PersonalityTrait>AgentStore::traits()const{S s(db_,"SELECT key,value,plasticity FROM personality_traits ORDER BY key;");std::vector<PersonalityTrait>o;while(sqlite3_step(s.get())==SQLITE_ROW)o.push_back({col(s.get(),0),sqlite3_column_double(s.get(),1),sqlite3_column_double(s.get(),2)});return o;}
void AgentStore::append_reflection(const Reflection&v){S s(db_,"INSERT OR REPLACE INTO reflections VALUES(?,?,?,?,?);");txt(s.get(),1,v.id);txt(s.get(),2,v.observation);txt(s.get(),3,v.lesson);sqlite3_bind_double(s.get(),4,v.confidence);txt(s.get(),5,v.created_at);check(sqlite3_step(s.get()),db_,"reflection");}std::vector<Reflection>AgentStore::reflections(std::size_t n)const{S s(db_,"SELECT id,observation,lesson,confidence,created_at FROM reflections ORDER BY created_at DESC LIMIT ?;");sqlite3_bind_int64(s.get(),1,static_cast<sqlite3_int64>(n));std::vector<Reflection>o;while(sqlite3_step(s.get())==SQLITE_ROW)o.push_back({col(s.get(),0),col(s.get(),1),col(s.get(),2),sqlite3_column_double(s.get(),3),col(s.get(),4)});return o;}
} // namespace exotic::cognition
