#include "exotic/cognition/belief_revision.hpp"
#include <sqlite3.h>
#include <algorithm>
#include <cmath>
#include <stdexcept>
namespace exotic::cognition {namespace {void schema(sqlite3*d){char*e=nullptr;const char*q="CREATE TABLE IF NOT EXISTS belief_evidence(id TEXT PRIMARY KEY,belief_id TEXT NOT NULL,source TEXT NOT NULL,statement TEXT NOT NULL,direction REAL NOT NULL,reliability REAL NOT NULL,observed_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS belief_revision_history(id INTEGER PRIMARY KEY AUTOINCREMENT,belief_id TEXT NOT NULL,before_proposition TEXT NOT NULL,after_proposition TEXT NOT NULL,before_confidence REAL NOT NULL,after_confidence REAL NOT NULL,rationale TEXT NOT NULL,created_at TEXT NOT NULL);";if(sqlite3_exec(d,q,nullptr,nullptr,&e)!=SQLITE_OK){std::string m=e?e:"schema";sqlite3_free(e);throw std::runtime_error(m);}}sqlite3*open(const std::string&p){sqlite3*d=nullptr;if(sqlite3_open(p.c_str(),&d)!=SQLITE_OK)throw std::runtime_error("belief revision db open failed");schema(d);return d;}}
BeliefRevisionProposal BeliefRevisionCapability::consider(const std::string&id,const std::vector<BeliefEvidence>&ev,std::string alt)const{BeliefRevisionProposal p;p.belief_id=id;for(const auto&b:store_.beliefs())if(b.id==id){p.old_proposition=b.proposition;p.old_confidence=b.confidence;break;}p.proposed_proposition=alt.empty()?p.old_proposition:alt;double s=0,w=0;for(const auto&e:ev){if(e.belief_id!=id)continue;double r=std::clamp(e.reliability,0.0,1.0);s+=std::clamp(e.direction,-1.0,1.0)*r;w+=r;p.evidence.push_back(e);}double delta=w>0?(s/w)*std::min(.20,.05*w):0;p.proposed_confidence=std::clamp(p.old_confidence+delta,0.0,1.0);p.rationale="Evidence provenance supports reconsideration; applying this proposal remains an explicit choice.";return p;}
bool BeliefRevisionCapability::apply(const BeliefRevisionProposal&p,const std::string&at){if(p.belief_id.empty()||p.old_proposition.empty())return false;sqlite3*d=open(store_.path());sqlite3_exec(d,"BEGIN IMMEDIATE",nullptr,nullptr,nullptr);sqlite3_stmt*s=nullptr;sqlite3_prepare_v2(d,"INSERT OR IGNORE INTO belief_evidence VALUES(?,?,?,?,?,?,?)",-1,&s,nullptr);for(const auto&e:p.evidence){sqlite3_reset(s);sqlite3_bind_text(s,1,e.id.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,e.belief_id.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,3,e.source.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,4,e.statement.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_double(s,5,e.direction);sqlite3_bind_double(s,6,e.reliability);sqlite3_bind_text(s,7,e.observed_at.c_str(),-1,SQLITE_TRANSIENT);sqlite3_step(s);}sqlite3_finalize(s);sqlite3_prepare_v2(d,"INSERT INTO belief_revision_history(belief_id,before_proposition,after_proposition,before_confidence,after_confidence,rationale,created_at) VALUES(?,?,?,?,?,?,?)",-1,&s,nullptr);sqlite3_bind_text(s,1,p.belief_id.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,p.old_proposition.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,3,p.proposed_proposition.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_double(s,4,p.old_confidence);sqlite3_bind_double(s,5,p.proposed_confidence);sqlite3_bind_text(s,6,p.rationale.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,7,at.c_str(),-1,SQLITE_TRANSIENT);bool ok=sqlite3_step(s)==SQLITE_DONE;sqlite3_finalize(s);sqlite3_exec(d,ok?"COMMIT":"ROLLBACK",nullptr,nullptr,nullptr);sqlite3_close(d);if(!ok)return false;store_.upsert_belief({p.belief_id,p.proposed_proposition,p.proposed_confidence,"provenance: belief_evidence",at});return true;}
std::vector<BeliefRevisionRecord> BeliefRevisionCapability::history(const std::string&id)const{sqlite3*d=open(store_.path());sqlite3_stmt*s=nullptr;std::string q="SELECT id,belief_id,before_proposition,after_proposition,before_confidence,after_confidence,rationale,created_at FROM belief_revision_history"+(id.empty()?std::string(""):" WHERE belief_id=?")+" ORDER BY id";sqlite3_prepare_v2(d,q.c_str(),-1,&s,nullptr);if(!id.empty())sqlite3_bind_text(s,1,id.c_str(),-1,SQLITE_TRANSIENT);std::vector<BeliefRevisionRecord>o;while(sqlite3_step(s)==SQLITE_ROW)o.push_back({std::to_string(sqlite3_column_int64(s,0)),reinterpret_cast<const char*>(sqlite3_column_text(s,1)),reinterpret_cast<const char*>(sqlite3_column_text(s,2)),reinterpret_cast<const char*>(sqlite3_column_text(s,3)),sqlite3_column_double(s,4),sqlite3_column_double(s,5),reinterpret_cast<const char*>(sqlite3_column_text(s,6)),reinterpret_cast<const char*>(sqlite3_column_text(s,7))});sqlite3_finalize(s);sqlite3_close(d);return o;}
} // namespace exotic::cognition
