#include "exotic/cognition/idle_cognition.hpp"
#include "exotic/cognition/attention_store.hpp"
#include "exotic/cognition/cognitive_budget.hpp"
#include "exotic/cognition/self_model.hpp"
#include <algorithm>
#include <chrono>
#include <cmath>
#include <string>
namespace exotic::cognition {
bool IdleCognitionScheduler::should_run(bool externally_busy) const {if(externally_busy)return false;const auto drives=store_.drives();return std::any_of(drives.begin(),drives.end(),[](const DriveRecord&d){return std::abs(d.target-d.level)>=.10;})||!store_.goals().empty()||!store_.beliefs().empty();}
std::optional<ThoughtCandidate> IdleCognitionScheduler::next_candidate() const {DevelopmentalSelfModel self(store_);self.consolidate();self.reflect();self.generate_candidate_goals();const auto goals=store_.goals();const auto beliefs=store_.beliefs();const auto preferences=store_.preferences();const auto active=std::find_if(goals.begin(),goals.end(),[](const PersistentGoal&g){return g.status=="active";});if(active!=goals.end())return ThoughtCandidate{"idle-goal-"+active->id,"Advance goal: "+active->title,active->priority,.45,.65,.35,.05,.40,.05};const auto uncertain=std::find_if(beliefs.rbegin(),beliefs.rend(),[](const BeliefRecord&b){return b.confidence<.70;});if(uncertain!=beliefs.rend())return ThoughtCandidate{"idle-belief-"+uncertain->id,"Re-evaluate belief: "+uncertain->proposition,.55,1.0-uncertain->confidence,.75,.30,.10,.55,.05};if(!preferences.empty()){const auto strongest=std::max_element(preferences.begin(),preferences.end(),[](const auto&a,const auto&b){return std::abs(a.weight)<std::abs(b.weight);});return ThoughtCandidate{"idle-preference-"+strongest->key,"Reflect on preference: "+strongest->key,std::min(1.0,std::abs(strongest->weight)),.35,.45,.55,.05,.50,.05};}return std::nullopt;}
std::optional<IdleAgencyCycle> IdleCognitionScheduler::agency_cycle(bool externally_busy,std::int64_t now,bool persist_choice){if(!should_run(externally_busy))return std::nullopt;auto c=next_candidate();if(!c)return std::nullopt;AttentionStore persisted_attention(store_);CognitiveBudget budget(1.0);for(const auto&s:persisted_attention.load())budget.restore_topic(s);auto attention=budget.consider(c->id,now,std::clamp(c->compute_cost+.05,0.05,1.0),c->novelty);for(const auto&s:budget.topic_states())if(s.topic_id==c->id)persisted_attention.save(s);if(attention.disposition!=AttentionDisposition::Consider)return std::nullopt;c->novelty=std::clamp(c->novelty*attention.novelty_multiplier,0.0,1.0);VolitionOption option{c->id,c->subject,std::clamp(c->goal_relevance,0.0,1.0),0.0,std::clamp(c->novelty,0.0,1.0),0.0,std::clamp(c->information_gain,0.0,1.0),std::clamp(c->compute_cost,0.0,1.0),std::clamp(c->risk_attention,0.0,1.0)};AgencyInput in;in.subject=c->subject;in.options={option};in.uncertainty=c->uncertainty;in.stakes=c->risk_attention;in.now=now;in.external_action_requested=false;in.explicit_external_grant=false;AgencyExecutive executive(store_);auto cycle=executive.consider(in);bool persisted=false;if(persist_choice){executive.remember_choice(c->subject,cycle.volition,std::to_string(now));persisted=true;}return IdleAgencyCycle{*c,std::move(cycle),persisted};}
void IdleCognitionScheduler::stop_topic(const std::string&id){AttentionStore storage(store_);CognitiveBudget budget;for(const auto&s:storage.load())budget.restore_topic(s);budget.stop_topic(id);for(const auto&s:budget.topic_states())if(s.topic_id==id)storage.save(s);}
void IdleCognitionScheduler::resume_topic(const std::string&id){AttentionStore storage(store_);CognitiveBudget budget;for(const auto&s:storage.load())budget.restore_topic(s);budget.resume_topic(id);for(const auto&s:budget.topic_states())if(s.topic_id==id)storage.save(s);}
void IdleCognitionScheduler::apply_reward(double reward){const auto tick=std::chrono::steady_clock::now().time_since_epoch().count();DevelopmentalSelfModel self(store_);self.remember({"reward-episode-"+std::to_string(tick),reward>=0.0?"Operator feedback was recorded as evidence about a recent cognitive pattern.":"Operator feedback was recorded as negative evidence about a recent cognitive pattern.",std::clamp(.55+std::abs(reward)*.35,0.0,1.0),std::clamp(reward,-1.0,1.0),""});}
}  // namespace exotic::cognition
