#include "exotic/cognition/intention.hpp"
#include <sqlite3.h>
#include <algorithm>
#include <stdexcept>
namespace exotic::cognition { namespace {
void ck(int rc,sqlite3*db,const char*w){if(rc!=SQLITE_OK&&rc!=SQLITE_DONE&&rc!=SQLITE_ROW)throw std::runtime_error(std::string(w)+": "+sqlite3_errmsg(db));}
class DB{public:explicit DB(const std::string&p){ck(sqlite3_open(p.c_str(),&d_),d_,"open intentions db");char*e=nullptr;const char*sql="CREATE TABLE IF NOT EXISTS choice_history(id TEXT PRIMARY KEY,subject TEXT NOT NULL,option_id TEXT NOT NULL,outcome TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL,supersedes TEXT NOT NULL DEFAULT '');CREATE TABLE IF NOT EXISTS intentions(id TEXT PRIMARY KEY,subject TEXT NOT NULL,source_choice_id TEXT NOT NULL,state TEXT NOT NULL,strength REAL NOT NULL CHECK(strength BETWEEN 0 AND 1),reason TEXT NOT NULL);";if(sqlite3_exec(d_,sql,nullptr,nullptr,&e)!=SQLITE_OK){std::string m=e?e:"schema";sqlite3_free(e);throw std::runtime_error(m);}}~DB(){if(d_)sqlite3_close(d_);}sqlite3*get()const{return d_;}private:sqlite3*d_{};};
class ST{public:ST(sqlite3*d,const char*q){ck(sqlite3_prepare_v2(d,q,-1,&s_,nullptr),d,"prepare");d_=d;}~ST(){sqlite3_finalize(s_);}sqlite3_stmt*get()const{return s_;}sqlite3*d_{};sqlite3_stmt*s_{};};
void tx(sqlite3_stmt*s,int i,const std::string&v){sqlite3_bind_text(s,i,v.c_str(),-1,SQLITE_TRANSIENT);}std::string col(sqlite3_stmt*s,int i){auto*p=sqlite3_column_text(s,i);return p?reinterpret_cast<const char*>(p):"";}
std::string out(VolitionOutcome o){switch(o){case VolitionOutcome::Choose:return"choose";case VolitionOutcome::Defer:return"defer";case VolitionOutcome::Reject:return"reject";default:return"do_nothing";}}
VolitionOutcome parse(const std::string&s){if(s=="choose")return VolitionOutcome::Choose;if(s=="defer")return VolitionOutcome::Defer;if(s=="reject")return VolitionOutcome::Reject;return VolitionOutcome::DoNothing;}
}
ChoiceHistoryRecord IntentionManager::record_choice(const std::string&subject,const VolitionDecision&d,const std::string&created,std::string supersedes){DB db(store_.path());const auto n=choices().size()+1;ChoiceHistoryRecord r{"choice-"+std::to_string(n),subject,d.option_id,d.outcome,d.rationale,created,std::move(supersedes)};ST s(db.get(),"INSERT INTO choice_history VALUES(?,?,?,?,?,?,?);");tx(s.get(),1,r.id);tx(s.get(),2,r.subject);tx(s.get(),3,r.option_id);tx(s.get(),4,out(r.outcome));tx(s.get(),5,r.reason);tx(s.get(),6,r.created_at);tx(s.get(),7,r.supersedes);ck(sqlite3_step(s.get()),db.get(),"choice");return r;}
Intention IntentionManager::propose_intention(const ChoiceHistoryRecord&c,double strength,const std::string&reason){Intention i{"intention-"+c.id,c.subject,c.id,"tentative",std::clamp(strength,0.0,1.0),reason};DB db(store_.path());ST s(db.get(),"INSERT OR REPLACE INTO intentions VALUES(?,?,?,?,?,?);");tx(s.get(),1,i.id);tx(s.get(),2,i.subject);tx(s.get(),3,i.source_choice_id);tx(s.get(),4,i.state);sqlite3_bind_double(s.get(),5,i.strength);tx(s.get(),6,i.reason);ck(sqlite3_step(s.get()),db.get(),"intention");return i;}
static bool set_state(AgentStore&store,const std::string&id,const std::string&state,const std::string&reason){DB db(store.path());ST s(db.get(),"UPDATE intentions SET state=?,reason=? WHERE id=?;");tx(s.get(),1,state);tx(s.get(),2,reason);tx(s.get(),3,id);ck(sqlite3_step(s.get()),db.get(),"intention state");return sqlite3_changes(db.get())>0;}
bool IntentionManager::commit(const std::string&id,const std::string&r){return set_state(store_,id,"committed",r);}bool IntentionManager::suspend(const std::string&id,const std::string&r){return set_state(store_,id,"suspended",r);}bool IntentionManager::abandon(const std::string&id,const std::string&r){return set_state(store_,id,"abandoned",r);}
std::vector<Intention> IntentionManager::intentions()const{DB db(store_.path());ST s(db.get(),"SELECT id,subject,source_choice_id,state,strength,reason FROM intentions ORDER BY rowid;");std::vector<Intention>v;while(sqlite3_step(s.get())==SQLITE_ROW)v.push_back({col(s.get(),0),col(s.get(),1),col(s.get(),2),col(s.get(),3),sqlite3_column_double(s.get(),4),col(s.get(),5)});return v;}
std::vector<ChoiceHistoryRecord> IntentionManager::choices()const{DB db(store_.path());ST s(db.get(),"SELECT id,subject,option_id,outcome,reason,created_at,supersedes FROM choice_history ORDER BY rowid;");std::vector<ChoiceHistoryRecord>v;while(sqlite3_step(s.get())==SQLITE_ROW)v.push_back({col(s.get(),0),col(s.get(),1),col(s.get(),2),parse(col(s.get(),3)),col(s.get(),4),col(s.get(),5),col(s.get(),6)});return v;}
} // namespace exotic::cognition
