#include "exotic/cognition/intention.hpp"
#include "exotic/cognition/stable_id.hpp"
#include "exotic/cognition/storage_schema.hpp"
#include <sqlite3.h>
#include <algorithm>
#include <chrono>
#include <stdexcept>
namespace exotic::cognition { namespace {
void ck(int rc,sqlite3*db,const char*w){if(rc!=SQLITE_OK&&rc!=SQLITE_DONE&&rc!=SQLITE_ROW)throw std::runtime_error(std::string(w)+": "+sqlite3_errmsg(db));}
class DB{public:explicit DB(const std::string&p){ck(sqlite3_open(p.c_str(),&d_),d_,"open intentions db");try{apply_storage_migrations(d_);}catch(...){sqlite3_close(d_);d_=nullptr;throw;}}~DB(){if(d_)sqlite3_close(d_);}sqlite3*get()const{return d_;}private:sqlite3*d_{};};
class ST{public:ST(sqlite3*d,const char*q){ck(sqlite3_prepare_v2(d,q,-1,&s_,nullptr),d,"prepare");d_=d;}~ST(){sqlite3_finalize(s_);}sqlite3_stmt*get()const{return s_;}sqlite3*d_{};sqlite3_stmt*s_{};};
void tx(sqlite3_stmt*s,int i,const std::string&v){sqlite3_bind_text(s,i,v.c_str(),-1,SQLITE_TRANSIENT);}std::string col(sqlite3_stmt*s,int i){auto*p=sqlite3_column_text(s,i);return p?reinterpret_cast<const char*>(p):"";}
std::string out(VolitionOutcome o){switch(o){case VolitionOutcome::Choose:return"choose";case VolitionOutcome::Defer:return"defer";case VolitionOutcome::Reject:return"reject";default:return"do_nothing";}}
VolitionOutcome parse(const std::string&s){if(s=="choose")return VolitionOutcome::Choose;if(s=="defer")return VolitionOutcome::Defer;if(s=="reject")return VolitionOutcome::Reject;return VolitionOutcome::DoNothing;}
std::string now_text(){return std::to_string(std::chrono::system_clock::now().time_since_epoch().count());}
bool allowed(const std::string&from,const std::string&to){if(from==to)return false;if(from=="tentative")return to=="committed"||to=="suspended"||to=="abandoned";if(from=="committed")return to=="suspended"||to=="abandoned"||to=="completed";if(from=="suspended")return to=="committed"||to=="abandoned";return false;}
}
ChoiceHistoryRecord IntentionManager::record_choice(const std::string&subject,const VolitionDecision&d,const std::string&created,std::string supersedes){DB db(store_.path());ChoiceHistoryRecord r{stable_id("choice"),subject,d.option_id,d.outcome,d.rationale,created,std::move(supersedes)};ST s(db.get(),"INSERT INTO choice_history VALUES(?,?,?,?,?,?,?);");tx(s.get(),1,r.id);tx(s.get(),2,r.subject);tx(s.get(),3,r.option_id);tx(s.get(),4,out(r.outcome));tx(s.get(),5,r.reason);tx(s.get(),6,r.created_at);tx(s.get(),7,r.supersedes);ck(sqlite3_step(s.get()),db.get(),"choice");return r;}
Intention IntentionManager::propose_intention(const ChoiceHistoryRecord&c,double strength,const std::string&reason){Intention i{stable_id("intention"),c.subject,c.id,"tentative",std::clamp(strength,0.0,1.0),reason};DB db(store_.path());ST s(db.get(),"INSERT INTO intentions VALUES(?,?,?,?,?,?);");tx(s.get(),1,i.id);tx(s.get(),2,i.subject);tx(s.get(),3,i.source_choice_id);tx(s.get(),4,i.state);sqlite3_bind_double(s.get(),5,i.strength);tx(s.get(),6,i.reason);ck(sqlite3_step(s.get()),db.get(),"intention");return i;}
static bool set_state(AgentStore&store,const std::string&id,const std::string&state,const std::string&reason){DB db(store.path());std::string from;{ST q(db.get(),"SELECT state FROM intentions WHERE id=?;");tx(q.get(),1,id);if(sqlite3_step(q.get())!=SQLITE_ROW)return false;from=col(q.get(),0);}if(!allowed(from,state))return false;ck(sqlite3_exec(db.get(),"BEGIN IMMEDIATE",nullptr,nullptr,nullptr),db.get(),"begin transition");try{ST u(db.get(),"UPDATE intentions SET state=?,reason=? WHERE id=?;");tx(u.get(),1,state);tx(u.get(),2,reason);tx(u.get(),3,id);ck(sqlite3_step(u.get()),db.get(),"intention state");ST h(db.get(),"INSERT INTO intention_transitions(id,intention_id,from_state,to_state,reason,created_at) VALUES(?,?,?,?,?,?);");tx(h.get(),1,stable_id("transition"));tx(h.get(),2,id);tx(h.get(),3,from);tx(h.get(),4,state);tx(h.get(),5,reason);tx(h.get(),6,now_text());ck(sqlite3_step(h.get()),db.get(),"transition history");ck(sqlite3_exec(db.get(),"COMMIT",nullptr,nullptr,nullptr),db.get(),"commit transition");return true;}catch(...){sqlite3_exec(db.get(),"ROLLBACK",nullptr,nullptr,nullptr);throw;}}
bool IntentionManager::commit(const std::string&id,const std::string&r){return set_state(store_,id,"committed",r);}bool IntentionManager::suspend(const std::string&id,const std::string&r){return set_state(store_,id,"suspended",r);}bool IntentionManager::abandon(const std::string&id,const std::string&r){return set_state(store_,id,"abandoned",r);}
std::vector<Intention> IntentionManager::intentions()const{DB db(store_.path());ST s(db.get(),"SELECT id,subject,source_choice_id,state,strength,reason FROM intentions ORDER BY rowid;");std::vector<Intention>v;while(sqlite3_step(s.get())==SQLITE_ROW)v.push_back({col(s.get(),0),col(s.get(),1),col(s.get(),2),col(s.get(),3),sqlite3_column_double(s.get(),4),col(s.get(),5)});return v;}
std::vector<ChoiceHistoryRecord> IntentionManager::choices()const{DB db(store_.path());ST s(db.get(),"SELECT id,subject,option_id,outcome,reason,created_at,supersedes FROM choice_history ORDER BY rowid;");std::vector<ChoiceHistoryRecord>v;while(sqlite3_step(s.get())==SQLITE_ROW)v.push_back({col(s.get(),0),col(s.get(),1),col(s.get(),2),parse(col(s.get(),3)),col(s.get(),4),col(s.get(),5),col(s.get(),6)});return v;}
} // namespace exotic::cognition
